build:
  version: "2.0"

accounts:
  message: "QA properties"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@dummy.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371