build:
  version: "3.0"

accounts:
  message: "default properties"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@dummy.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
