build:
  version: "1.0"

cards:
  message: "prod properties"
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@dummy.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721