build:
  version: "3.0"

cards:
  message: "default properties "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@dummy.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932