build:
  version: "2.0"

cards:
  message: "QA properties"
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@dummy.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267