build:
  version: "1.0"

loans:
  message: "prod properties"
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@dummy.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956