build:
  version: "3.0"

loans:
  message: "default properties"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@dummy.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934