spring:
  application:
    name: "configserver"
  profiles:
    active: native # config files in classpath
#    active: git # config files in git server
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/altonchan1998/microservices-config
#          username: altonchan1998
#          password: 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
#          clone-on-start: true
#          default-label: main # branch of the config repo
#          uri: https://github.com/${GIT_ACCOUNT}/${GIT_REPO}
#          username: ${GIT_ACCOUNT}
#          password: ${GIT_PASSWORD}
        native:
          searchLocations: classpath:/config # location of config files in repository
#          searchLocations: file:///C:/config # location of config files in local system

management: # For actuator
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"